### ISSUE TITLE
Display abilities

### ISSUE THREAD

**Issue by Karlsson2** [Karlsson2/react-pokedex#19]
display abilities when accessing the pokemon object on each individual page.

the pokemon object is called pokemon, the abilities are under pokemon.abilities. It will be necesary to loop over these as there might be multiple abilities.

Display the ability names under the "Types" section.

<img width="786" alt="image" src="https://github.com/user-attachments/assets/e445c9a6-0a2f-4bf2-9950-fa56ed04a8df">

**Comment by GeorgiosDrivas** [comment]
Hello @Karlsson2 ! I would like to work on this issue.

**Comment by Karlsson2** [comment]
I have assigned it to you @GeorgiosDrivas follow instructions in regards to contributions in the readme 😊

**Comment by GeorgiosDrivas** [comment]
Just a check for the UI before the pull request. Which one do you prefer?

![screen2](https://github.com/user-attachments/assets/07eec3ad-0426-4965-b3c7-4a9768b457d3)
![screen1](https://github.com/user-attachments/assets/1f750019-5221-4a9a-8ef9-0e7f5ba95127)

I believe the second is better, so that it will look like categories for each tab.

**Comment by Karlsson2** [comment]
Yes the second looks better 😊

**Comment by Karlsson2** [comment]
Sorted :)
